### ISSUE TITLE
Wie kann ich die App nutzen?

### ISSUE THREAD

**Issue by ks-2097** [mwiedemeyer/FamilienDuell#1]
Hallo,

ich würde die App gerne für eine Hochzeit nutzen, aber ich bin nicht sicher, wie ich sie nutzen soll?

Muss ich sie noch irgendwie kompilieren? Ich versuche mich gerade mit Visual Studio Code und Google durchzuwurschteln aber bisher ohne Erfolg.

**Comment by mwiedemeyer** [comment]
Du findest es unter Releases oder direkt hier: https://github.com/mwiedemeyer/FamilienDuell/releases/download/v1.0/FamilienDuell.zip

**Comment by ks-2097** [comment]
Die App ist der Hammer!!!

**Comment by ks-2097** [comment]
Es gibt so ein paar kleine glitches wie z.B. das die Punkte nicht direkt untereinander sind.
![image](https://user-images.githubusercontent.com/23033712/89389977-67d4db00-d706-11ea-9a59-900b3fd42e22.png)

Im Original sind auch die underscores leicht getrennt.

Zuletzt könnte man diese Schweinchen noch als Zwischenscreen mit einfügen?

Wenn ich selber zu dem Projekt contributen möchte, geht das auch in VS Code oder brauche ich zwingend Visual Studio?

**Comment by mwiedemeyer** [comment]
Könnte man sicher alles machen, war halt eher so hingehackt, dass es für meinen Fall mit dem Design passte. Du brauchst Visual Studio (Community Edition ist kostenlos und ausreichend): https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16

Dort hast du zumindest einen Designer.

**Comment by ks-2097** [comment]
Okay, ich probiere mal mein Glück. 

Es gibt ja auch noch die Finalrunde zu programmieren :)
